# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: felps
# "service" is the name of this project. This will also be added to your AWS resource names.
service: gestapp-api

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

build:
  esbuild: false

provider:
  name: aws
  runtime: nodejs20.x

custom:
  esbuild:
    target: node20
    format: esm
    minify: true
    outputFileExtension: .mjs

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
