spring.datasource.url=jdbc:postgresql://ep-lively-block-125000-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?prepareThreshold=0
spring.datasource.username=default
spring.datasource.password=3SqPxZpAWsQ9

spring.jpa.hibernate.ddl-auto=update

jwt.secret=felps
